---
- name: Ensure admin user exists
  ansible.builtin.user:
    name: "{{ admin_user }}"
    groups: "{{ admin_user_groups }}"
    append: true
    shell: "{{ admin_user_shell }}"
    state: present
    create_home: true
  tags:
    - users
    - accounts

- name: Ensure admin user SSH directory exists
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/.ssh"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0700'
    state: directory
  tags:
    - users
    - ssh_keys

- name: Install admin user SSH public key
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: "{{ admin_ssh_public_key }}"
  tags:
    - users
    - ssh_keys

- name: Configure sudo access for admin user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ admin_user }}"
    owner: root
    group: root
    mode: '0440'
    content: "{{ admin_user }} ALL=(ALL) ALL\n"
    validate: /usr/sbin/visudo -cf %s
  tags:
    - users
    - sudoers
