[admin]
admin-01 ansible_host=192.168.0.201

[monitoring]
monitor-01 ansible_host=192.168.0.202

[rocky]
admin-01
monitor-01

[rocky:vars]
ansible_user=jocufe
ansible_ssh_private_key_file=~/.ssh/ansible_admin01
