---
- import_playbook: base-rocky.yml
- import_playbook: users.yml
- import_playbook: ssh-hardening.yml
- import_playbook: firewall.yml
- import_playbook: system-update.yml
- import_playbook: node_exporter.yml
- import_playbook: prometheus.yml
